import {
  BitcoinNetwork,
  jdcDataDir,
  jdcAuthorityPublicKey,
  jdcAuthoritySecretKey,
  jdcMonitoringPort,
  jdcPort,
  workerHashrateExtension,
} from './utils'

type JdcBase = {
  username: string
  sharesPerMinute: number
  jdcSignature: string
  coinbaseRewardAddress: string
  network: BitcoinNetwork
}

export type JdcConfig =
  | (JdcBase & { kind: 'solo' })
  | (JdcBase & {
      kind: 'jd-pool'
      poolAuthorityPubkey: string
      poolAddress: string
      poolPort: number
      jdsPort: number
    })

const tomlFloat = (n: number): string =>
  Number.isInteger(n) ? `${n}.0` : `${n}`

// SOLOMINING mines to the user's own address with no pool; FULLTEMPLATE declares
// user-built templates to a pool's JD server while the pool handles payout.
export function generateJdcToml(c: JdcConfig): string {
  const solo = c.kind === 'solo'
  const upstreams = solo
    ? 'upstreams = []'
    : `[[upstreams]]
authority_pubkey = "${c.poolAuthorityPubkey}"
pool_address = "${c.poolAddress}"
pool_port = ${c.poolPort}
jds_address = "${c.poolAddress}"
jds_port = ${c.jdsPort}
user_identity = "${c.username}"`

  return `# JD Client Configuration (${solo ? 'sovereign solo mining' : 'job declaration with pool'})
# Generated by StartOS

listening_address = "127.0.0.1:${jdcPort}"

max_supported_version = 2
min_supported_version = 2

authority_public_key = "${jdcAuthorityPublicKey}"
authority_secret_key = "${jdcAuthoritySecretKey}"
cert_validity_sec = 3600

shares_per_minute = ${tomlFloat(c.sharesPerMinute)}
share_batch_size = 10

mode = "${solo ? 'SOLOMINING' : 'FULLTEMPLATE'}"

jdc_signature = "${c.jdcSignature}"

coinbase_reward_script = "addr(${c.coinbaseRewardAddress})"

supported_extensions = [${workerHashrateExtension}]

monitoring_address = "0.0.0.0:${jdcMonitoringPort}"
monitoring_cache_refresh_secs = 15

${upstreams}

[template_provider_type.BitcoinCoreIpc]
version = 31
network = "${c.network}"
data_dir = "${jdcDataDir}"
fee_threshold = 100
min_interval = 5
`
}
