import {
  BitcoinNetwork,
  bitcoindIpcDataDir,
  jdcAuthorityPublicKey,
  jdcAuthoritySecretKey,
  jdcPort,
} from './utils'

export type JdcSoloConfig = {
  username: string
  sharesPerMinute: number
  jdcSignature: string
  coinbaseRewardAddress: string
  network: BitcoinNetwork
}

const tomlFloat = (n: number): string =>
  Number.isInteger(n) ? `${n}.0` : `${n}`

// Sovereign solo mining: JDC pulls templates from Bitcoin Core over IPC and
// mines to the user's address. No pool/JDS upstreams.
export function generateJdcSoloToml(c: JdcSoloConfig): string {
  return `# JD Client Configuration (sovereign solo mining)
# Generated by StartOS

listening_address = "127.0.0.1:${jdcPort}"

max_supported_version = 2
min_supported_version = 2

authority_public_key = "${jdcAuthorityPublicKey}"
authority_secret_key = "${jdcAuthoritySecretKey}"
cert_validity_sec = 3600

user_identity = "${c.username}"

shares_per_minute = ${tomlFloat(c.sharesPerMinute)}
share_batch_size = 10

mode = "SOLOMINING"

jdc_signature = "${c.jdcSignature}"

coinbase_reward_script = "addr(${c.coinbaseRewardAddress})"

supported_extensions = []

monitoring_address = "0.0.0.0:9091"
monitoring_cache_refresh_secs = 15

upstreams = []

[template_provider_type.BitcoinCoreIpc]
network = "${c.network}"
data_dir = "${bitcoindIpcDataDir}"
fee_threshold = 1000
min_interval = 5
`
}
