import { monitoringPort, stratumPort } from './utils'

export type PoolConfig = {
  poolAddress: string
  poolPort: number
  poolAuthorityPubkey: string
  username: string
  minHashrateThs: number
  sharesPerMinute: number
  extranonce2Size: number
  aggregateChannels: boolean
}

const tomlFloat = (n: number): string =>
  Number.isInteger(n) ? `${n}.0` : `${n}`

export function generateTranslatorToml(cfg: PoolConfig): string {
  const minHashrate = tomlFloat(Math.round(cfg.minHashrateThs * 1e12))
  const sharesPerMinute = cfg.sharesPerMinute.toFixed(1)
  const extranonce2Size = Math.max(1, Math.trunc(cfg.extranonce2Size))

  return `# Translator Proxy Configuration
# Generated by StartOS

downstream_address = "0.0.0.0"
downstream_port = ${stratumPort}

max_supported_version = 2
min_supported_version = 2

downstream_extranonce2_size = ${extranonce2Size}

user_identity = "${cfg.username}"

aggregate_channels = ${cfg.aggregateChannels}

supported_extensions = []
required_extensions = []

monitoring_address = "0.0.0.0:${monitoringPort}"
monitoring_cache_refresh_secs = 15

[downstream_difficulty_config]
min_individual_miner_hashrate = ${minHashrate}
shares_per_minute = ${sharesPerMinute}
enable_vardiff = true
job_keepalive_interval_secs = 60

[[upstreams]]
address = "${cfg.poolAddress}"
port = ${cfg.poolPort}
authority_pubkey = "${cfg.poolAuthorityPubkey}"
`
}
